complexity:
  ComplexCondition:
    threshold: 6
  NestedBlockDepth:
    threshold: 6
  TooManyFunctions:
    thresholdInClasses: 15

empty-blocks:
  active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
  RethrowCaughtException:
    active: false

naming:
  PackageNaming:
    active: false

style:
  ReturnCount:
    max: 4
  ForbiddenComment:
    active: false
  UnnecessaryAbstractClass:
    active: false

potential-bugs:
  UnsafeCallOnNullableType:
    active: false

formatting:
  active: true
  Indentation:
    active: true
